version: '3.9'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  examplenodeapp1:
    restart: on-failure
    build: ./examplenodeapp1
    ports:
      - '81:5000'
  examplenodeapp2:
    restart: on-failure
    build: ./examplenodeapp2
    ports:
      - '82:5000'
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - examplenodeapp1
    - examplenodeapp2